version: '3.8'

services:
  api:
    container_name: poke_trader_api_prod
    build: ./api
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./api:/api
      - api_node_modules:/api/node_modules
    env_file: prod.env
    command: ["sh","-c", "yarn && node src/index.js"]
  
  front:
    container_name: poke_trader_front_prod
    build: ./front
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - ./front:/front/
      - front_node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001

volumes: 
  api_node_modules:
  front_node_modules:


