version: '3.8'

services:
  api:
    container_name: poke_trader_api
    build: ./api
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./api:/api
      - api_node_modules:/api/node_modules
    env_file: .env
    networks: 
      - poke_trader_network
    depends_on:
      - db

  db:
    container_name: poke_trader_db
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    env_file: .env
    volumes:
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./db/.dbshell:/home/mongodb/.dbshell
      - mongodb:/data/db
    networks:
      - poke_trader_network
  
  front:
    container_name: poke_trader_front
    build: ./front
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - ./front:/front/
      - front_node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001

volumes: 
  api_node_modules:
  front_node_modules:
  mongodb:

networks: 
  poke_trader_network:

